---
# ==========================
# Proxmox
# ==========================

proxmox_host: 192.168.40.21
proxmox_user: root@pam
proxmox_password: UniversalQ1w2@

node: pve

# ==========================
# Template
# ==========================

template_name: ubuntu26-cloudinit
template_vmid: 9000

# ==========================
# Cloud Image
# ==========================

cloud_image_url: https://cloud-images.ubuntu.com/releases/resolute/release/ubuntu-26.04-server-cloudimg-amd64.img
cloud_image_path: /var/lib/vz/template/iso/ubuntu-26.04-server-cloudimg-amd64.img

# ==========================
# Storage
# ==========================

disk_storage: local-lvm
disk_size_gb: 30

# ==========================
# VM
# ==========================

memory: 4096
cores: 2
onboot: true

bridge: vmbr1
vlan_tag: 30

# ==========================
# Network
# ==========================

subnet_base: 192.168.30
ip_start_host: 150

netmask_cidr: 24
gateway_ip: 192.168.30.1

dns_server: 8.8.8.8
dns_searchdomain: local.lan

# ==========================
# Cloud-init
# ==========================

ci_user: root
ci_password: rootnow

# File public key berada di Proxmox
ci_ssh_pubkey_path: /root/.ssh/id_ed25519.pub

# ==========================
# Clone
# ==========================

vm_count: 3
vmid_start: 401
vm_name_prefix: ubuntu
ansible_user: root
